apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcast-app
  namespace: devops
spec:
  selector:
    matchLabels:
      app: webcast-app
  template:
    metadata:
      labels:
        app: webcast-app
    spec:
      nodeName: bams
      containers:
      - name: webcast-app
        image: opeoniye/dclm-webcast:$BUILD_NUMBER
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webcast-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: webcast-app
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webcast-ingress
  namespace: devops
spec:
  ingressClassName: nginx
  rules:
  - host: "webcast.k8s"
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: webcast-service
              port:
                number: 80